### ISSUE TITLE
Suggestion: Add option to perform autofocus with outward movements.

### ISSUE THREAD

**Issue by philbart61** [ghilios/joko.nina.plugins#10]
Hi George,

Thank you for your great focusing routines.

I have recently purchased an EdgeHD SCT and focus using an Zwo EAF attached to main focus knob which moves the primary mirror. It works very well. To use this method, a large "IN" backlash needs to be entered so that the final focuser movement is outwards, lifting the mirror against gravity.

Unfortunately, when the focus points start OUT and move IN, this means the large backlash has to be removed at every focus point. With the EAF focuser this is very slow. If there was an option to reverse the direction of the focus points, starting low  (IN) and moving higher (OUT), then backlash removal is only required at the beginning of the focusing routine and at the end, not at every focus point.

I tried using a negative value in the Autofocus Step Size, which was accepted. This caused errors in HocusFocus. It sort of worked with the standard NINA routines, but when it tried to add extra points to the start/end of the curve it did not seem to work and repeated focus positions already performed (either it wasn't intended to have a -ve value entered, or hadn't been tested fully with a -ve step size).

Please let me know if this is not clear and if this change is possible in Hocus Focus.

Regards,
Philip

**Comment by astrodet** [comment]
Hi philbart61, I use the same equipment and solved the problem by configuring the EAF to "reverse direction". This makes insofar sense as every poitive stepcount moves the primary mirror back decreasing the focal length of the telecope. So nearer objects get into focus. That is similar to extenting  a classical focuser drawtube in a virtual refractor.

**Comment by philbart61** [comment]
Hi George. Thank you, this solved my problem.
