### ISSUE TITLE
Store settings in NINA profile

### ISSUE THREAD

**Issue by Ruediger3** [ghilios/joko.nina.plugins#2]
Hello,
I am creating this issue based on Bitbucket issue #1061: https://bitbucket.org/Isbeorn/nina/issues/1061/store-plugin-configurations-along-with

I would appreciate if the settings would be stored along the NINA profile, since I work with multiple NINA instances parallelly and I have to reenter setting for each scope again on every start. e.g. PixelScale "Long Focal Range"

Thank you for considering.

Regards
Rüdiger

**Comment by Ruediger3** [comment]
Hello George,
I have update the Bitbucket issue.
Rüdiger

**Comment by Ruediger3** [comment]
Any update on this issue?
Rüdiger

**Comment by ghilios** [comment]
Hey Ruediger, sorry I didn't notice the messages here. I deployed a fix already. Are you on the latest version (21)?

**Comment by Ruediger3** [comment]
Hello George,

yes I have updated to 21. Just tested and now it looks fine. Many thanks for fixing :)

Cheers
Rüdiger
